<div class="alert alert-info">

# PSY 3019/6973-G-H24
# Cueillette et traitement des données en neurosciences cognitives
## Chapitre 3: Modification de données
<p>
<li> Modification des données
<li> Combinaison des données
<li> Pandas groupby

<div class="alert alert-info">
<h3>Modifications de données</h3></div>

<div class="alert alert-warning">
<h3>modification des valeurs des chaînes</h3>
</div>

In [1]:
a = "bonjour"
a

'bonjour'

In [2]:
a[3] = "T"

# la chaîne est un objet immuable

TypeError: 'str' object does not support item assignment

In [4]:
a.index("j")

3

In [3]:
# remplacement des données dans la chaîne

a.replace("njo","nTo")

'bonTour'

In [4]:
# chaîne -> liste

a.split("n")

['bo', 'jour']

<div class="alert alert-warning">
<h3>modification des valeurs d'une liste</h3>
</div>

In [6]:
ls1 = [3, 2, 1, 0]

In [7]:
# ajout de données

ls1.append('text-ver2')
ls1

[3, 2, 1, 0, 'text-ver2']

In [8]:
# changement de données

ls1[1] = 7
print(ls1)

[3, 7, 1, 0, 'text-ver2']


In [ ]:
# faire des copies

ls2 = ls1.copy()

In [26]:
ls1.remove(3)

In [28]:
# ls1

In [23]:
ls1 = [3, 2, 1, 0]

ls1.pop(2)
ls1

In [9]:
ls1 = [3, 2, 1, 0]

ls1.sort()
ls1

[0, 1, 2, 3]

In [28]:
ls1.reverse()
ls1

<div class="alert alert-warning">
<h3>modification des valeurs d'un tuple</h3>
</div>

In [10]:
tup1 = (3, 2, 1, 0)
tup1[1] = 7

TypeError: 'tuple' object does not support item assignment

In [11]:
# faire des copies

tup2 = tup1
print(tup2)

(3, 2, 1, 0)


In [12]:
tup1.remove(3)

# Les tuples ne peuvent être changés, une fois définis
# Les tuples sont habituellement plus rapides que les listes

AttributeError: 'tuple' object has no attribute 'remove'

<div class="alert alert-warning">
<h3>modification des valeurs d'un dictionnaire</h3>
</div>

In [18]:
# ajout des valeurs
d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }

d1['autre'] = 'valeur2'
d1

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2'}

In [14]:
# changements des valeurs:

d1['cle1'] = 'var 2'
d1['cle1']

'var 2'

In [42]:
# donnee la valeur de la clé SI elle existe

var = d1.get('cle3')
var

[1, 2, 3]

In [ ]:
# supprimer une clé du dictionnaire SI elle existe

d1.pop('cle4')
d1

In [15]:
d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }

del d1['cle4']
d1

{'cle1': 'variable', 'cle2': [], 'cle3': [1, 2, 3]}

In [19]:
print(len(d1), len(d1['cle1']))

5 8


In [16]:
# supprimer tous les élements du dictionnaire

d1.clear()
d1

{}

In [20]:
# faire des copies

d3 = d1

In [21]:
d1

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2'}

In [22]:
d3

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2'}

In [23]:
d3['kqyky'] = 4.0
d3

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2',
 'kqyky': 4.0}

In [24]:
d1

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2',
 'kqyky': 4.0}

In [16]:
# créer une copie superficielle

d3 = d1.copy()

In [ ]:
# créer une copie complète

d3 = d1.deepcopy()

In [ ]:
import copy
d3 = copy.deepcopy(d1)

# Il faut créer une copie indépendante
# Sinon, les modifications apportées au dictionnaire copié
# vont également être envoyées à la version d'origine

In [ ]:
# plus d'info sur la différence entre copy et deepcopy

https://thispointer.com/python-how-to-copy-a-dictionary-shallow-copy-vs-deep-copy/
https://stackabuse.com/deep-vs-shallow-copies-in-python/#:~:text=Deep%20copy%20stores%20copies%20of%20an%20object's%20values,,implementation,%20I'd%20like%20you%20to%20imagine%20this%20scenario.
http://tech.quebecblogue.com/python-tips-copie-superficielle-copie-profonde-dans-python3/
https://www.ipgirl.com/675/quelle-est-la-difference-entre-une-copie-profonde-et-une-copie-superficielle.html    

<div class="alert alert-warning">
<h3>modification des valeurs d'un pandas DataFrame</h3>
    <li>loc (location)
    <li>iloc (index location)
    <li>at
</div>

In [25]:
import pandas

In [28]:
fichier = 'data/projinfrarechrapprou20200527.csv'
df_qc = pandas.read_csv(fichier)

In [29]:
df_qc.ETABLISSEMENT[1]

'École Polytechnique de Montréal'

In [30]:
# pour montrer la colonne

df_qc['ETABLISSEMENT']

0       Université du Québec à Chicoutimi (UQAC)
1                École Polytechnique de Montréal
2                       Université de Sherbrooke
3                       Université de Sherbrooke
4                               Université Laval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [31]:
# semblable à la précédente; loc = location
    
df_qc.loc[:, 'ETABLISSEMENT']

0       Université du Québec à Chicoutimi (UQAC)
1                École Polytechnique de Montréal
2                       Université de Sherbrooke
3                       Université de Sherbrooke
4                               Université Laval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [32]:
df_qc.iloc[1:]              
# affiche toutes les lignes de 1 :; iloc = index-location

REGION_ADMINISTRATIVE                           ETABLISSEMENT  \
1                 Montréal         École Polytechnique de Montréal   
2                   Estrie                Université de Sherbrooke   
3                   Estrie                Université de Sherbrooke   
4       Capitale-Nationale                        Université Laval   
5                 Montréal                       Université McGill   
...                    ...                                     ...   
1310              Montréal                  Université de Montréal   
1311              Montréal                  Université de Montréal   
1312              Montréal         École Polytechnique de Montréal   
1313              Montréal                  Université de Montréal   
1314     Bas-Saint-Laurent  Université du Québec à Rimouski (UQAR)   

                               ETABLISSEMENT_PARTENAIRE ANNEE_FINANCIERE  \
1                                                   NaN        2009-2010   
2                                                   NaN        2009-2010   
3                                                   NaN        2009-2010   
4                                                   NaN        2009-2010   
5                                                   NaN        2009-2010   
...                                                 ...              ...   
1310                                                NaN        2018-2019   
1311                                                NaN        2018-2019   
1312                                                NaN        2018-2019   
1313  CIUSSS de l'Est-de-l'Île-de-Montréal - Institu...        2018-2019   
1314                                                NaN        2018-2019   

                            PROGRAMME  \
1     Fonds des initiatives nouvelles   
2     Fonds des initiatives nouvelles   
3     Fonds des initiatives nouvelles   
4     Fonds des initiatives nouvelles   
5              Fonds de l'avant-garde   
...                               ...   
1310  Fonds des leaders John-R.-Evans   
1311  Fonds des leaders John-R.-Evans   
1312  Fonds des leaders John-R.-Evans   
1313  Fonds des leaders John-R.-Evans   
1314  Fonds des leaders John-R.-Evans   

                                             VOLET     RESPONSABLE_DU_PROJET  \
1                                              NaN            Ludvik MARTINU   
2                                              NaN     André Dieter BANDRAUK   
3                                              NaN               Alain BERRY   
4                                              NaN         Marc-André SIRARD   
5                                              NaN              David THOMAS   
...                                            ...                       ...   
1310  Indépendant - chercheur junior - recrutement        Pierre-Luc CHAGNON   
1311  Indépendant - chercheur junior - recrutement              Ahmad Hamdan   
1312  Indépendant - chercheur junior - recrutement        Keyhan SHESHYEKANI   
1313  Indépendant - chercheur junior - recrutement        Robert Paul Juster   
1314                Indépendant - chercheur établi  Martin-Hugues ST-LAURENT   

                                                  TITRE RESEAU  MONTANT_MEES  \
1     Système de revêtements intelligents pour des s...   MEES     1067986.0   
2     Infrastructure pour modélisation et visualisat...   MEES     2377939.0   
3     Vibroacoustique des structures multi-matériaux...   MEES     1644690.0   
4     Laboratoire de physiologie intégrative en scie...   MEES     2203653.0   
5     Le Complexe des sciences de la vie de l'Univer...   MEES    10632949.0   
...                                                 ...    ...           ...   
1310  Comment les traits des champignons mycorhizien...   MEES      114771.0   
1311  Infrastructure de recherche sur les plasmas mu...   MEES      233586.0   
1312                        Laboratoire de microréseaux   MEES      125000.0 

In [33]:
df_qc.iloc[0:, [1,2]]
# affiche les lignes de 0 à : et les colonnes 1 et 2

# iloc fonctionne seulement avec les positions

ETABLISSEMENT  \
0     Université du Québec à Chicoutimi (UQAC)   
1              École Polytechnique de Montréal   
2                     Université de Sherbrooke   
3                     Université de Sherbrooke   
4                             Université Laval   
...                                        ...   
1310                    Université de Montréal   
1311                    Université de Montréal   
1312           École Polytechnique de Montréal   
1313                    Université de Montréal   
1314    Université du Québec à Rimouski (UQAR)   

                               ETABLISSEMENT_PARTENAIRE  
0                                                   NaN  
1                                                   NaN  
2                                                   NaN  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
1310                                                NaN  
1311                                                NaN  
1312                                                NaN  
1313  CIUSSS de l'Est-de-l'Île-de-Montréal - Institu...  
1314                                                NaN  

[1315 rows x 2 columns]

In [34]:
df_qc.at[0,'ETABLISSEMENT']
# permet l'accès aux cellules

'Université du Québec à Chicoutimi (UQAC)'

In [107]:
col = df_qc.columns[1]

df_qc[col][:3]

0    Université du Québec à Chicoutimi (UQAC)
1             École Polytechnique de Montréal
2                    Université de Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [108]:
df_qc.ETABLISSEMENT

0       Université du Québec à Chicoutimi (UQAC)
1                École Polytechnique de Montréal
2                       Université de Sherbrooke
3                       Université de Sherbrooke
4                               Université Laval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [36]:
df_qc.loc[1, 'ETABLISSEMENT'] = 'POLY'

In [37]:
df_qc.at[2, 'ETABLISSEMENT'] = 'Sherbrooke'

In [38]:
df_qc.iloc[4, 1] = 'ULaval'

In [39]:
df_qc.ETABLISSEMENT

0       Université du Québec à Chicoutimi (UQAC)
1                                           POLY
2                                     Sherbrooke
3                       Université de Sherbrooke
4                                         ULaval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [40]:
df_qc2 = df_qc

In [41]:
df_qc.ETABLISSEMENT.head(3)

0    Université du Québec à Chicoutimi (UQAC)
1                                        POLY
2                                  Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [42]:
df_qc2.ETABLISSEMENT.head(3)

0    Université du Québec à Chicoutimi (UQAC)
1                                        POLY
2                                  Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [43]:
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'

In [44]:
df_qc2.at[1, 'ETABLISSEMENT']

'poly_new'

In [45]:
df_qc.at[1, 'ETABLISSEMENT']

'poly_new'

In [ ]:
# faire des copies

df_qc = pandas.read_csv(fichier)
df_qc2 = df_qc.copy(deep=True)
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'
df_qc2.ETABLISSEMENT[1]
df_qc.ETABLISSEMENT[1]

In [ ]:
import copy
df_qc2 = copy.deepcopy(df_qc)
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'

In [46]:
df_qc3 = pandas.read_csv(fichier, usecols = ['ETABLISSEMENT', 'COUT_TOTAL'])

In [47]:
df_qc3.columns

Index(['ETABLISSEMENT', 'COUT_TOTAL'], dtype='object')

In [48]:
df_qc4 = df_qc[["ETABLISSEMENT", "ETABLISSEMENT_PARTENAIRE",
       'ANNEE_FINANCIERE', 'PROGRAMME', 'VOLET', 'RESPONSABLE_DU_PROJET',
       'TITRE', 'RESEAU', 'MONTANT_MEES', 'MONTANT_MSSS', 'MONTANT_MEI',
       'MONTANT_TOTAL_QUEBEC', 'COUT_TOTAL']]

In [49]:
df_qc4.columns

Index(['ETABLISSEMENT', 'ETABLISSEMENT_PARTENAIRE', 'ANNEE_FINANCIERE',
       'PROGRAMME', 'VOLET', 'RESPONSABLE_DU_PROJET', 'TITRE', 'RESEAU',
       'MONTANT_MEES', 'MONTANT_MSSS', 'MONTANT_MEI', 'MONTANT_TOTAL_QUEBEC',
       'COUT_TOTAL'],
      dtype='object')

In [51]:
# df.department.tolist()

ls_df = df_qc4.ETABLISSEMENT.tolist()
ls_df

['Université du Québec à Chicoutimi (UQAC)',
 'poly_new',
 'Sherbrooke',
 'Université de Sherbrooke',
 'ULaval',
 'Université McGill',
 'École Polytechnique de Montréal',
 'École Polytechnique de Montréal',
 'École Polytechnique de Montréal',
 'Université de Montréal',
 'Université de Montréal',
 'École Polytechnique de Montréal',
 'Université du Québec à Montréal (UQAM)',
 'Université de Montréal',
 'Université McGill',
 'Université du Québec en Outaouais (UQO)',
 'Université Laval',
 'Université de Montréal',
 'Université McGill',
 'Université de Sherbrooke',
 'Université de Sherbrooke',
 'Université du Québec à Montréal (UQAM)',
 'Université Laval',
 'HEC Montréal',
 'Université Concordia',
 'Université de Montréal',
 'Université du Québec à Montréal (UQAM)',
 'Université Laval',
 'École de technologie supérieure (ETS)',
 'Université de Sherbrooke',
 'Télé-Université',
 'Université de Montréal',
 'Université de Montréal',
 'Université de Montréal',
 'École de technologie supérieure 

In [52]:
ls_df = list(df_qc.items())

In [53]:
ls_df[1]

('ETABLISSEMENT',
 0       Université du Québec à Chicoutimi (UQAC)
 1                                       poly_new
 2                                     Sherbrooke
 3                       Université de Sherbrooke
 4                                         ULaval
                           ...                   
 1310                      Université de Montréal
 1311                      Université de Montréal
 1312             École Polytechnique de Montréal
 1313                      Université de Montréal
 1314      Université du Québec à Rimouski (UQAR)
 Name: ETABLISSEMENT, Length: 1315, dtype: object)

In [55]:
# création d'une nouvelle colonne appelée «autre»

df_qc2['autre'] = 'valeur2'
df_qc2['autre'][:5]

0    valeur2
1    valeur2
2    valeur2
3    valeur2
4    valeur2
Name: autre, dtype: object

In [56]:
df_qc

REGION_ADMINISTRATIVE                             ETABLISSEMENT  \
0     Saguenay-Lac-Saint-Jean  Université du Québec à Chicoutimi (UQAC)   
1                    Montréal                                  poly_new   
2                      Estrie                                Sherbrooke   
3                      Estrie                  Université de Sherbrooke   
4          Capitale-Nationale                                    ULaval   
...                       ...                                       ...   
1310                 Montréal                    Université de Montréal   
1311                 Montréal                    Université de Montréal   
1312                 Montréal           École Polytechnique de Montréal   
1313                 Montréal                    Université de Montréal   
1314        Bas-Saint-Laurent    Université du Québec à Rimouski (UQAR)   

                               ETABLISSEMENT_PARTENAIRE ANNEE_FINANCIERE  \
0                                                   NaN        2009-2010   
1                                                   NaN        2009-2010   
2                                                   NaN        2009-2010   
3                                                   NaN        2009-2010   
4                                                   NaN        2009-2010   
...                                                 ...              ...   
1310                                                NaN        2018-2019   
1311                                                NaN        2018-2019   
1312                                                NaN        2018-2019   
1313  CIUSSS de l'Est-de-l'Île-de-Montréal - Institu...        2018-2019   
1314                                                NaN        2018-2019   

                            PROGRAMME  \
0              Fonds de l'avant-garde   
1     Fonds des initiatives nouvelles   
2     Fonds des initiatives nouvelles   
3     Fonds des initiatives nouvelles   
4     Fonds des initiatives nouvelles   
...                               ...   
1310  Fonds des leaders John-R.-Evans   
1311  Fonds des leaders John-R.-Evans   
1312  Fonds des leaders John-R.-Evans   
1313  Fonds des leaders John-R.-Evans   
1314  Fonds des leaders John-R.-Evans   

                                             VOLET     RESPONSABLE_DU_PROJET  \
0                                              NaN              Hubert MORIN   
1                                              NaN            Ludvik MARTINU   
2                                              NaN     André Dieter BANDRAUK   
3                                              NaN               Alain BERRY   
4                                              NaN         Marc-André SIRARD   
...                                            ...                       ...   
1310  Indépendant - chercheur junior - recrutement        Pierre-Luc CHAGNON   
1311  Indépendant - chercheur junior - recrutement              Ahmad Hamdan   
1312  Indépendant - chercheur junior - recrutement        Keyhan SHESHYEKANI   
1313  Indépendant - chercheur junior - recrutement        Robert Paul Juster   
1314                Indépendant - chercheur établi  Martin-Hugues ST-LAURENT   

                                                  TITRE RESEAU  MONTANT_MEES  \
0     Développement de l'infrastructure de recherche...   MEES      583172.0   
1     Système de revêtements intelligents pour des s...   MEES     1067986.0   
2     Infrastructure pour modélisation et visualisat...   MEES     2377939.0   
3     Vibroacoustique des structures multi-matériaux...   MEES     1644690.0   
4     Laboratoire de physiologie intégrative en scie...   MEES     2203653.0   
...                                                 ...    ...           ...   
1310  Comment les traits des champignons mycorhizien...   MEES      114771.0   
1311  Infrastructure de recherche sur les plasmas mu...   MEES      233586.0   
1312                

In [57]:
# modification d'index

df_qc.set_index('ETABLISSEMENT')

# le cadre de donn/es df_qc n<est pas change

REGION_ADMINISTRATIVE  \
ETABLISSEMENT                                                       
Université du Québec à Chicoutimi (UQAC)  Saguenay-Lac-Saint-Jean   
poly_new                                                 Montréal   
Sherbrooke                                                 Estrie   
Université de Sherbrooke                                   Estrie   
ULaval                                         Capitale-Nationale   
...                                                           ...   
Université de Montréal                                   Montréal   
Université de Montréal                                   Montréal   
École Polytechnique de Montréal                          Montréal   
Université de Montréal                                   Montréal   
Université du Québec à Rimouski (UQAR)          Bas-Saint-Laurent   

                                                                   ETABLISSEMENT_PARTENAIRE  \
ETABLISSEMENT                                                                                 
Université du Québec à Chicoutimi (UQAC)                                                NaN   
poly_new                                                                                NaN   
Sherbrooke                                                                              NaN   
Université de Sherbrooke                                                                NaN   
ULaval                                                                                  NaN   
...                                                                                     ...   
Université de Montréal                                                                  NaN   
Université de Montréal                                                                  NaN   
École Polytechnique de Montréal                                                         NaN   
Université de Montréal                    CIUSSS de l'Est-de-l'Île-de-Montréal - Institu...   
Université du Québec à Rimouski (UQAR)                                                  NaN   

                                         ANNEE_FINANCIERE  \
ETABLISSEMENT                                               
Université du Québec à Chicoutimi (UQAC)        2009-2010   
poly_new                                        2009-2010   
Sherbrooke                                      2009-2010   
Université de Sherbrooke                        2009-2010   
ULaval                                          2009-2010   
...                                                   ...   
Université de Montréal                          2018-2019   
Université de Montréal                          2018-2019   
École Polytechnique de Montréal                 2018-2019   
Université de Montréal                          2018-2019   
Université du Québec à Rimouski (UQAR)          2018-2019   

                                                                PROGRAMME  \
ETABLISSEMENT                                                               
Université du Québec à Chicoutimi (UQAC)           Fonds de l'avant-garde   
poly_new                                  Fonds des initiatives nouvelles   
Sherbrooke                                Fonds des initiatives nouvelles   
Université de Sherbrooke                  Fonds des initiatives nouvelles   
ULaval                                    Fonds des initiatives nouvelles   
...                                                                   ...   
Université de Montréal                    Fonds des leaders John-R.-Evans   
Université de Montréal                    Fonds des leaders John-R.-Evans   
École Polytechnique de Montréal           Fonds des leaders John-R.-Evans   
Université de Montréal                    Fonds des leaders John-R.-Evans   
Université du Québec à Rimouski (UQAR)    Fonds des leaders John-R.-Evans   

                                                                                 VOLET  \
ETABLISSEMENT           

In [145]:
df_qc

In [157]:
df_qc.set_index('ETABLISSEMENT', inplace = True)

In [64]:
df_qc3 = df_qc.set_index('ETABLISSEMENT')

In [58]:
df_qc

REGION_ADMINISTRATIVE                             ETABLISSEMENT  \
0     Saguenay-Lac-Saint-Jean  Université du Québec à Chicoutimi (UQAC)   
1                    Montréal                                  poly_new   
2                      Estrie                                Sherbrooke   
3                      Estrie                  Université de Sherbrooke   
4          Capitale-Nationale                                    ULaval   
...                       ...                                       ...   
1310                 Montréal                    Université de Montréal   
1311                 Montréal                    Université de Montréal   
1312                 Montréal           École Polytechnique de Montréal   
1313                 Montréal                    Université de Montréal   
1314        Bas-Saint-Laurent    Université du Québec à Rimouski (UQAR)   

                               ETABLISSEMENT_PARTENAIRE ANNEE_FINANCIERE  \
0                                                   NaN        2009-2010   
1                                                   NaN        2009-2010   
2                                                   NaN        2009-2010   
3                                                   NaN        2009-2010   
4                                                   NaN        2009-2010   
...                                                 ...              ...   
1310                                                NaN        2018-2019   
1311                                                NaN        2018-2019   
1312                                                NaN        2018-2019   
1313  CIUSSS de l'Est-de-l'Île-de-Montréal - Institu...        2018-2019   
1314                                                NaN        2018-2019   

                            PROGRAMME  \
0              Fonds de l'avant-garde   
1     Fonds des initiatives nouvelles   
2     Fonds des initiatives nouvelles   
3     Fonds des initiatives nouvelles   
4     Fonds des initiatives nouvelles   
...                               ...   
1310  Fonds des leaders John-R.-Evans   
1311  Fonds des leaders John-R.-Evans   
1312  Fonds des leaders John-R.-Evans   
1313  Fonds des leaders John-R.-Evans   
1314  Fonds des leaders John-R.-Evans   

                                             VOLET     RESPONSABLE_DU_PROJET  \
0                                              NaN              Hubert MORIN   
1                                              NaN            Ludvik MARTINU   
2                                              NaN     André Dieter BANDRAUK   
3                                              NaN               Alain BERRY   
4                                              NaN         Marc-André SIRARD   
...                                            ...                       ...   
1310  Indépendant - chercheur junior - recrutement        Pierre-Luc CHAGNON   
1311  Indépendant - chercheur junior - recrutement              Ahmad Hamdan   
1312  Indépendant - chercheur junior - recrutement        Keyhan SHESHYEKANI   
1313  Indépendant - chercheur junior - recrutement        Robert Paul Juster   
1314                Indépendant - chercheur établi  Martin-Hugues ST-LAURENT   

                                                  TITRE RESEAU  MONTANT_MEES  \
0     Développement de l'infrastructure de recherche...   MEES      583172.0   
1     Système de revêtements intelligents pour des s...   MEES     1067986.0   
2     Infrastructure pour modélisation et visualisat...   MEES     2377939.0   
3     Vibroacoustique des structures multi-matériaux...   MEES     1644690.0   
4     Laboratoire de physiologie intégrative en scie...   MEES     2203653.0   
...                                                 ...    ...           ...   
1310  Comment les traits des champignons mycorhizien...   MEES      114771.0   
1311  Infrastructure de recherche sur les plasmas mu...   MEES      233586.0   
1312                

In [59]:
df_qc.index[1]

1

In [60]:
df_qc.at[1, 'COUT_TOTAL']

2725474

In [24]:
df_qc.index

In [65]:
df_qc3.at['École Polytechnique de Montréal', 'COUT_TOTAL']

ETABLISSEMENT
École Polytechnique de Montréal     2725474
École Polytechnique de Montréal     2733818
École Polytechnique de Montréal     3950656
École Polytechnique de Montréal     3648864
École Polytechnique de Montréal     8481600
École Polytechnique de Montréal      322332
École Polytechnique de Montréal      259525
École Polytechnique de Montréal    12406827
École Polytechnique de Montréal      537323
École Polytechnique de Montréal     7329611
École Polytechnique de Montréal     6846945
École Polytechnique de Montréal      995480
École Polytechnique de Montréal      795760
École Polytechnique de Montréal      999993
École Polytechnique de Montréal      513316
École Polytechnique de Montréal      478143
École Polytechnique de Montréal      329818
École Polytechnique de Montréal      998680
École Polytechnique de Montréal      403241
École Polytechnique de Montréal      814165
École Polytechnique de Montréal      317654
École Polytechnique de Montréal      322641
École Polytechniqu

In [145]:
df_qc.to_excel('chemin/tmp2.xls')
df_qc.to_csv('chemin/tmp2.csv')

<div class="alert alert-warning">
<h3>modification des valeurs d'un tableau Numpy</h3>
<li> np.reshape
<li> np.newaxis
<li> copy
<li> changer les éléments
</div>

In [1]:
import numpy as np

In [5]:
x1 = np.random.randint(10, size = 6) #tableau 1D

In [3]:
x1_2D = x1.reshape((2,3))
x1_2D

array([[3, 8, 7],
       [3, 0, 6]])

In [4]:
x1_2D2 = np.reshape(x1, (3, -1))
# -1 décide automatiquement le nombre de cols

x1_2D2

array([[3, 8],
       [7, 3],
       [0, 6]])

In [6]:
# np.newaxis pour convertir un tableau 1D
# en un vecteur de ligne ou colonne

x1[:,np.newaxis]

array([[6],
       [4],
       [9],
       [9],
       [2],
       [5]])

In [7]:
# changer de plus grandes tables

mon_tab = np.array(((6, 12, 93, 2),
                    (5, 26, 78, 90),
                    (3, 12, 16, 22),
                    (5, 3, 1, 16)))
mon_tab

array([[ 6, 12, 93,  2],
       [ 5, 26, 78, 90],
       [ 3, 12, 16, 22],
       [ 5,  3,  1, 16]])

In [8]:
mon_tab.shape

(4, 4)

In [9]:
mon_tab_remodel = np.reshape(mon_tab, (8,2))

In [10]:
mon_tab_remodel

array([[ 6, 12],
       [93,  2],
       [ 5, 26],
       [78, 90],
       [ 3, 12],
       [16, 22],
       [ 5,  3],
       [ 1, 16]])

In [11]:
m3 = mon_tab[:, np.newaxis]
m3

array([[[ 6, 12, 93,  2]],

       [[ 5, 26, 78, 90]],

       [[ 3, 12, 16, 22]],

       [[ 5,  3,  1, 16]]])

In [12]:
m3.shape

(4, 1, 4)

In [13]:
mon_tab

array([[ 6, 12, 93,  2],
       [ 5, 26, 78, 90],
       [ 3, 12, 16, 22],
       [ 5,  3,  1, 16]])

In [79]:
np.reshape(mon_tab, (8,3))

ValueError: cannot reshape array of size 16 into shape (8,3)

In [14]:
np.reshape(mon_tab, (8,-1))

array([[ 6, 12],
       [93,  2],
       [ 5, 26],
       [78, 90],
       [ 3, 12],
       [16, 22],
       [ 5,  3],
       [ 1, 16]])

In [20]:
x2 = np.random.randint(10, size = (3,4))#tableau 2D

In [16]:
x2_v1 = x2[1:,2:].copy()

x2_v1

array([[6, 9],
       [2, 3]])

In [17]:
x2_v2 = x2[:2, :2].copy()
x2_v2

array([[2, 1],
       [6, 0]])

In [21]:
x2

array([[4, 0, 7, 2],
       [3, 3, 6, 3],
       [0, 5, 7, 9]])

In [22]:
x2[0,0] = 12
x2

array([[12,  0,  7,  2],
       [ 3,  3,  6,  3],
       [ 0,  5,  7,  9]])

In [23]:
x2[0,1] = 3.141
x2

# ? ou est la nouvelle valeur ?

array([[12,  3,  7,  2],
       [ 3,  3,  6,  3],
       [ 0,  5,  7,  9]])

<div class="alert alert-warning">
<b>REMARQUE ! </b>
<ul> contrairement aux listes, les tableaux numpy ont un type fixe, i.e., float in int = int</div>

<div class="alert alert-warning">
<b>trier les tableaux numpy</b>
<li> np.sort
<li> np.argsort</div>

In [24]:
a = np.array([2,5,3,7,5,3])

np.sort(a)

array([2, 3, 3, 5, 5, 7])

In [25]:
a.sort()
a

array([2, 3, 3, 5, 5, 7])

In [26]:
np.argsort(a)

#affiche les indices des éléments triés

array([0, 1, 2, 3, 4, 5])

<div class="alert alert-info">
<h3>Combinaison des données</h3></div>

<div class="alert alert-warning">
<h3>combiner les chaînes</h3>
</div>

In [33]:
text3, c, text4 = 'montreal', 4, '.ca'

In [34]:
text3

'montreal'

In [35]:
text3, c, text4

('montreal', 4, '.ca')

In [36]:
print(c)

4


In [37]:
print(text3+c)

TypeError: can only concatenate str (not "int") to str

In [38]:
print(text3+str(c))

montreal4


In [ ]:
# string() commands:

# len()
# strip()      # Les espaces de début sont supprimés
# strip(char)  # retourne une copie de la chaîne dans laquelle tous les caractères ont été supprimés du DÉBUT et de la FIN de la chaîne
# rstrip(char) # retourne une copie de la chaîne dans laquelle tous les caractères ont été supprimés de la FIN de la chaîne

# replace(char)
# split(char, char)
# find(char)
# isdigit()

In [ ]:
s = 'bonjour'
# len(s) 
# s.find(j)
# s.find('j')
# s.rstrip('ur')
# s.replace('b','c')

In [ ]:
# all string methods:
https://docs.python.org/2/library/string.html
https://docs.python.org/3/library/stdtypes.html
https://www.programiz.com/python-programming/methods/string

In [39]:
a = "aBDnnc" # contien des lettre minuscules

a.islower()

False

In [16]:
# ATTENTION avec strip(), rstrip()
# si la commande comprend plusieurs caractères,
# les caractères du milieu seront traités comme une commande de recherche

# ex2 = "texts.xlsx"
# ex2.strip(".xlsx")
# ex2.rstrip(".xlsx")

# ex3 = "textn.fini"
# ex3.strip(".fini")
# ex3.rstrip(".fini")

# ex4 = "textt.fiti"
# ex4.strip(".fiti")
# ex4.rstrip(".fiti")

# strip()  supprime les caractères du début et de la fin
# rstrip() supprime le caractères de la fin. # reverse strip()

'tex'

<div class="alert alert-warning">
<h3>combiner les entieres et les flottants</h3>
</div>

In [40]:
i = 30

In [41]:
ii = i+7
ii

37

In [42]:
f = 3.0
f

3.0

In [43]:
ff = f+8
ff

11.0

In [98]:
fff = ff+ii
fff

48.0

In [44]:
f/i

0.1

In [45]:
ff/f

3.6666666666666665

In [46]:
type(i)

int

In [47]:
fi = float(i)
fi

30.0

In [101]:
iff = int(f)
iff

3

In [102]:
type(i)

int

In [ ]:
type(f)

In [104]:
text3
type(text3)

str

In [ ]:
# integer methods:

https://docs.python.org/3/library/stdtypes.html

In [ ]:
a = 7676

a.bit_length()

In [48]:
m = 8.0
m.is_integer()

True

<div class="alert alert-warning">
<h3>combiner les listes</h3>
</div>

In [52]:
# concatenation:
ls1 = ['text1', 'b', 'text2', 'text',]

ls3 = ls1+ls1[2:]
ls3

['text1', 'b', 'text2', 'text', 'text2', 'text']

In [51]:
tup1 = ('text1', 'b', 'text2', 'text',)

tup3 = tup1+tup1[-2:]
tup3

('text1', 'b', 'text2', 'text', 'text2', 'text')

In [53]:
tup4 = ls1+tup1
tup4

TypeError: can only concatenate list (not "tuple") to list

In [ ]:
# commandes python utilisables sur les listes 
help(ls1)
len(ls)    # taille de la liste ls
sorted(ls) # enregistrera une liste triée

# commande spécifique pour les listes:
ls.sort    # affichera une liste triée mais ne l'enregistrera pas 
ls.append  # ajout d’un element à la fin de la liste ls
ls.reverse # inverser la liste ls
ls.index   # rechercher un élément dans la liste ls
ls.remove  # retirer un element de la liste ls
ls.pop     # retirer le dernier element de la liste ls

<center><img src="img/Tableau_comparaison_liste_tuple.png"></center>

<div class="alert alert-warning">
<h3>combiner les dictionnaires</h3>
</div>

In [ ]:
# La concaténation des dictionnaires peut comporter des erreurs
# Vérifiez la version de python.

In [56]:
x = {'a': 1, 'b': 2}
y = {'b': 3, 'c': 4}

In [57]:
# python >3.9

z = x | y
z

# ATTENTION!
# la valeur des clés avec le même nom
# prendra TOUJOURS la valeur du deuxième dictionnaire

{'a': 1, 'b': 3, 'c': 4}

In [58]:
# python >3.5

z = {**x, **y}
z

{'a': 1, 'b': 3, 'c': 4}

In [59]:
# la fusion peut être effectuée en incluant de nouvelles clés:

z = {**x, 'foo': 1, 'bar': 2, **y}
z

{'a': 1, 'b': 3, 'foo': 1, 'bar': 2, 'c': 4}

In [13]:
# python 2

z = x.copy()
z.update(y) 
z

In [ ]:
# pour une réponse plus complète:
# https://stackoverflow.com/questions/38987/how-do-i-merge-two-dictionaries-in-a-single-expression-take-union-of-dictionari

<div class="alert alert-warning">
<h3>combiner les pandas.DataFrame</h3>
</div>

<div class="alert alert-success">
<ul> <h5>Concat/ Append</h5>
<li> Concat donne la flexibilité de rejoindre les jeux de données en fonction de l'axe (toutes les lignes ou toutes les colonnes)
<p><p> pandas.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)<p>
<li> Append est le cas spécifique (axe = 0, join = 'outer') de concat. il a été écrit avant l'écriture de la fonction concat. il peut être supprimé dans les versions ultérieures.
<p><p> pandas.DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)</ul>
<p>
<ul> <h5>Merge/ Join</h5>
<li> Merge est basée sur une colonne particulière de chacun des deux cadres de données, ces colonnes sont des variables comme «left_on», «right_on», «on»
<p><p> pandas.DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)<p>
<li> Join est basée sur les index et sur la façon dont les variable se combinent =['left','right','inner','outer']. Utilisez le join pour la jointure index sur index (par défaut) et colonne (s) sur index. Si vous vous joignez uniquement à l'index, vous souhaiterez peut-être utiliser join pour vous éviter de taper.
<p><p> pandas.DataFrame.join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False)</ul></div>

In [61]:
import pandas

In [62]:
df_A = pandas.DataFrame({'a':5, 'b':2, 'c':1}, index = [0])
df_B = pandas.DataFrame({'a':3, 'b':4, 'c':2}, index = [0])
df_C = pandas.DataFrame({'a':7, 'b':2, 'c':8}, index = [0])

In [63]:
df_A.append(df_B)

a  b  c
0  5  2  1
0  3  4  2

In [64]:
df_Concat = pandas.concat([df_A, df_B], axis = 0)
# axis=0 is default - pour les colonnes

df_Concat

a  b  c
0  5  2  1
0  3  4  2

In [244]:
df_Concat = pandas.concat([df_A, df_B], axis = 1)
# axis=1 = pour l'index

df_Concat

a  b  c  a  b  c
0  1  2  2  3  4  2

In [65]:
pandas.concat([df_A, df_B],
              keys=['rouge','bleue'],
              axis=0)

a  b  c
rouge 0  5  2  1
bleue 0  3  4  2

In [66]:
df_office1 = pandas.DataFrame({'name':['Alana','Pierre','Corinne','Marianne'],
                           'group':['Bank','Science','Resources','Plannification']})
df_office2 = pandas.DataFrame({'name':['Alana','Pierre','Corinne','Marianne'],
                           'date':['2004','2008','2006','2012']})

In [67]:
pandas.concat([df_office1, df_office1])

name           group
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification

In [55]:
pandas.concat([df_office1, df_office1])

group      name
0            Bank     Alana
1         Science    Pierre
2       Resources   Corinne
3  Plannification  Marianne
0            Bank     Alana
1         Science    Pierre
2       Resources   Corinne
3  Plannification  Marianne

In [68]:
pandas.concat([df_office1, df_office2], axis=1)

name           group      name  date
0     Alana            Bank     Alana  2004
1    Pierre         Science    Pierre  2008
2   Corinne       Resources   Corinne  2006
3  Marianne  Plannification  Marianne  2012

In [69]:
df_office1.merge(df_office2)

name           group  date
0     Alana            Bank  2004
1    Pierre         Science  2008
2   Corinne       Resources  2006
3  Marianne  Plannification  2012

In [257]:
df_office1

name           group
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification

In [258]:
df_office2

name  date
0     Alana  2004
1    Pierre  2008
2   Corinne  2006
3  Marianne  2012

In [70]:
df_office1.join(df_office2.set_index('name'), on='name')

name           group  date
0     Alana            Bank  2004
1    Pierre         Science  2008
2   Corinne       Resources  2006
3  Marianne  Plannification  2012

<div class="alert alert-warning">
<h3>combiner les numpy.array</h3>
</div>

<div class="alert alert-warning">
<ul> <b>Concatenation </b></div>

In [71]:
# concaténation de tableaux

tab1 = np.array(((1, 2),
                 (3, 4)))
tab2 = np.array(((5, 6),
                 (7, 8)))
tab3 = np.array(((9, 10),
                 (11, 12)))

In [72]:
tab1.shape

(2, 2)

In [73]:
tab1

array([[1, 2],
       [3, 4]])

In [74]:
concat1 = np.concatenate((tab1, tab2, tab3))

In [75]:
concat1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [76]:
concat1.shape

(6, 2)

In [77]:
# concaténation de tableaux, different types

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(a, b,c)

[1 2 3] [4 5 6] [7 8 9]


<center><img src="img/numpy_vstack_hstack.png"><center>

In [78]:
np.vstack([a,b,c]) #concaténation vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
chk1 = np.vstack([a,b,c]) #concaténation vertical
print(chk1.shape, chk1.ndim)

(3, 3) 2


In [80]:
np.hstack([a,b,c]) #concaténation horizontale

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
chk_v = np.hstack([a,b,c]) #concaténation vertical
print(chk_v.shape, chk_v.ndim)

(9,) 1


In [101]:
np.c_[a,b,c] #concaténation vertical, Version 2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [102]:
np.r_[a,b,c] #concaténation horizontale, Version 2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<div class="alert alert-warning">
<b>Division de tableaux </b>
</div>

<div class="alert alert-success">
<li> np.split
<li> np.vsplit
<li> np.hsplit</div>

In [82]:
tab_concat = np.array(((1, 2),
                       (3, 4),
                       (5, 6),
                       (7, 8),
                       (9, 10),
                       (11, 12)))
tab_concat

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
tab_concat.shape, tab_concat.ndim

((6, 2), 2)

<center><img src="img/numpy_split.png"><center>

In [84]:
np.split(tab_concat, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

<center><img src="img/numpy_vsplit.png"><center>

In [85]:
# numpy.vsplit(ary, indices_or_sections)

np.vsplit(tab_concat, [3])

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [86]:
u1, u2 = np.vsplit(tab_concat, [3])
u1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
tab_concat

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

<center><img src="img/numpy_hsplit.png"><center>

In [81]:
u1, u2 = np.hsplit(tab_concat, [1])
u2

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])

<div class="alert alert-info">
<h3>Groupby: pandas.DataFrame.groupby</h3></div>

<div class="alert alert-success">
<li> DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, observed=False, **kwargs)

<p>

groupby s'effectue en 3 étapes:

<li> <b>fractionnement</b> pour scinder et grouper un Cadre de données en fonction de la valeur de la clé spécifiée
<li> <b>application</b> pour calculer une fonction (agrégat, transformation, filtrage, au sein des groupes individuels)
<li> <b>combinaison</b> fusionne les résultats dans un tableau de sortie.

In [56]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [264]:
#planets.method.tolist()

In [197]:
planets.to_excel('chemin/tmp3.xls')

In [57]:
planets.groupby('method').mean()

number  orbital_period      mass  \
method                                                              
Astrometry                     1.000000      631.180000       NaN   
Eclipse Timing Variations      1.666667     4751.644444  5.125000   
Imaging                        1.315789   118247.737500       NaN   
Microlensing                   1.173913     3153.571429       NaN   
Orbital Brightness Modulation  1.666667        0.709307       NaN   
Pulsar Timing                  2.200000     7343.021201       NaN   
Pulsation Timing Variations    1.000000     1170.000000       NaN   
Radial Velocity                1.721519      823.354680  2.630699   
Transit                        1.954660       21.102073  1.470000   
Transit Timing Variations      2.250000       79.783500       NaN   

                                  distance         year  
method                                                   
Astrometry                       17.875000  2011.500000  
Eclipse Timing Variations       315.360000  2010.000000  
Imaging                          67.715937  2009.131579  
Microlensing                   4144.000000  2009.782609  
Orbital Brightness Modulation  1180.000000  2011.666667  
Pulsar Timing                  1200.000000  1998.400000  
Pulsation Timing Variations            NaN  2007.000000  
Radial Velocity                  51.600208  2007.518987  
Transit                         599.298080  2011.236776  
Transit Timing Variations      1104.333333  2012.500000

In [265]:
planets.orbital_period[planets.method=='Astrometry'].mean()

631.1800000000001

In [266]:
planets.distance[planets.method=='Astrometry'].mean()

17.875

In [267]:
planets.groupby('method').groups.keys()

dict_keys(['Astrometry', 'Eclipse Timing Variations', 'Imaging', 'Microlensing', 'Orbital Brightness Modulation', 'Pulsar Timing', 'Pulsation Timing Variations', 'Radial Velocity', 'Transit', 'Transit Timing Variations'])

In [268]:
planets.groupby(['method','year']).first()

number  orbital_period  mass  distance
method                    year                                        
Astrometry                2010       1      1016.00000   NaN     14.98
                          2013       1       246.36000   NaN     20.77
Eclipse Timing Variations 2008       2      5767.00000   NaN    130.72
                          2009       1     10220.00000  6.05       NaN
                          2010       2      5573.55000   NaN    500.00
...                                ...             ...   ...       ...
Transit                   2014       1         3.57532   NaN    322.00
Transit Timing Variations 2011       2       160.00000   NaN   2119.00
                          2012       2        57.01100   NaN    855.00
                          2013       2        22.33950   NaN    339.00
                          2014       3             NaN   NaN       NaN

[69 rows x 4 columns]

In [ ]:
planets.groupby('method')['year'].describe()

In [269]:
#dispatch:

planets.groupby('method')['year'].describe().unstack()

       method                       
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...  
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

In [ ]:
# python commands:
# help(i)
sorted()

<div class="alert alert-danger">
<b>les commandes et codes à apprendre par cœur </b></div>

<div class="alert alert-danger">
<h3>Exercises</h3>
</div>

<div class="alert alert-success">
<li> Comment ajouter une variable à un tuple ?
<li> Triez et affichez la liste
<li> Ajoutez l’élément 12 à la liste et affichez la liste 
<li> Enlevez l’élément 38 et affichez la liste
<li>convertir un tableau 1D en tableau 2D avec 2 lignes
    </ul>
</div>

<div class="alert alert-success">
<li> Comment concaténer 2 listes ?
<li> Comment concaténer un tuple et une liste ?
<li> Quelles sont les commandes habituelles utilisées pour travailler avec une liste ?
<li> Quelles sont les commandes pour travailler avec une chaîne ?
</ul>
</div>

In [ ]:
# Trouvez l'erreur
list1 = ['1','2','3', 4, '5', 6, 'c']
list2 = ['a','b','c','d']
list3 = ('e','f','g','h')

print(list1+list2[3])
print(list1[3]+list2)
print(list1+list3)

<div class="alert alert-success">
<li> Décrivez les étapes du code 'CODE GROUPBY EXERCISE'
<li> Qu'est-ce que la fonction fillna() apportera au code final?
</div>

In [202]:
# CODE GROUPBY EXERCISE
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method' , decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

In [3]:
# Créez un cadre de données de pandas
# à partir  des éléments ci-dessous:

mydict = dict(zip(mylist, myarr))

In [114]:
# Combinez ls1 et dict1 pour former une base de données

ls1 = list('abcedfghijklmnopqrstuvwxyz')
dict1 = {i: [str(i)+'_'+str(i*2)] for i in range(1,len(ls1))}

Créez un tableau numpy 3 × 3 de tous les True

obtenir les positions de 2 élèments dans un tableau numpy, où les éléments A et B correspondent

joindre deux tableaux verticalement

In [ ]:
# réponses pour la quéstion dans chapitre 2

# version 1
d1 = {'Subj_ID':['001'],'score': [16], 'group': [2], 'condition': ['cognition']}
df_d = pandas.DataFrame(d1)

# version 2
d1 = {'Subj_ID':'001','score': 16, 'group': 2, 'condition': 'cognition'}
df_d = pandas.DataFrame(d1, index=[0])