<div class="alert alert-info">

# PSY 3019/6973-G-H24
# Cueillette et traitement des données en neurosciences cognitives
## Chapitre 3: Les opérateurs
<p>
<li>opérateurs de comparaison
    <li>opérateurs d'aggregation
    <li>opérateurs arithmétiques (incluses dans NumPy)
    <li>opérateurs trigonométrique; exponents, logarithms
    <li>opérateurs sur les valuers manquantes

<div class="alert alert-info">
<h3>opérateurs de comparaison</h3></div>

In [7]:
fichier = 'data/projinfrarechrapprou20200527.csv'
df_qc = pandas.read_csv(fichier)

df_qc = pandas.read_csv(fichier,
                        usecols = ['REGION_ADMINISTRATIVE', 'ETABLISSEMENT', "COUT_TOTAL"])

In [8]:
df_qc.columns

Index(['REGION_ADMINISTRATIVE', 'ETABLISSEMENT', 'COUT_TOTAL'], dtype='object')

In [4]:
# utiliser les méthodes de Bool pour examiner les 
# clés / indices et les valeurs - pour vérifier si la valeur est présente

'ETABLISSEMENT' in df_qc

True

In [5]:
'etab' in df_qc

False

In [9]:
df_qc[(df_qc["COUT_TOTAL"] > 1400000) & (df_qc["COUT_TOTAL"] < 5500000)]

REGION_ADMINISTRATIVE                             ETABLISSEMENT  \
0     Saguenay-Lac-Saint-Jean  Université du Québec à Chicoutimi (UQAC)   
1                    Montréal           École Polytechnique de Montréal   
3                      Estrie                  Université de Sherbrooke   
6                    Montréal           École Polytechnique de Montréal   
7                    Montréal           École Polytechnique de Montréal   
...                       ...                                       ...   
1216                Côte-Nord                        Cégep de Sept-Iles   
1217  Saguenay-Lac-Saint-Jean  Université du Québec à Chicoutimi (UQAC)   
1218               Montérégie                 Collège Édouard Montpetit   
1220       Capitale-Nationale                          Université Laval   
1250                   Estrie                  Université de Sherbrooke   

      COUT_TOTAL  
0        1457930  
1        2725474  
3        4248206  
6        2733818  
7        3950656  
...          ...  
1216     2471713  
1217     2990981  
1218     1585562  
1220     1984920  
1250     1583499  

[104 rows x 3 columns]

In [10]:
df_qc[df_qc.ETABLISSEMENT == 'Université de Montréal']

REGION_ADMINISTRATIVE           ETABLISSEMENT  COUT_TOTAL
9                 Montréal  Université de Montréal    22912123
10                Montréal  Université de Montréal     4596464
13                Montréal  Université de Montréal     9998513
17                Montréal  Université de Montréal     8576653
25                Montréal  Université de Montréal    11700123
...                    ...                     ...         ...
1294              Montréal  Université de Montréal      698421
1298              Montréal  Université de Montréal      127125
1310              Montréal  Université de Montréal      287517
1311              Montréal  Université de Montréal      583965
1313              Montréal  Université de Montréal      382425

[268 rows x 3 columns]

In [ ]:
df_qc[
    (df_qc.ETABLISSEMENT == 'Université de Montréal') &
    (df_qc.COUT_TOTAL < 100000)]

In [13]:
a = np.random.randint(10, size=8)

In [14]:
a

array([4, 5, 7, 5, 6, 6, 9, 3])

In [15]:
a < 4

array([False, False, False, False, False, False, False,  True])

In [89]:
a != 3

array([ True,  True,  True, False,  True,  True,  True,  True])

<div class="alert alert-info">
<h3>opérateurs d'aggregation</h3></div>

In [1]:
import seaborn as sns

# pip3 install seaborn

In [2]:
# lecture à partir de jeux de données de modules:

planets = sns.load_dataset('planets')

# # Alternative:
# planets = pandas.read_excel('/data/planets.xlsx')
# planets.set_index("Unnamed: 0", inplace = True)

planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [3]:
planets.to_excel("/home/ssp/Desktop/planets.xlsx", engine = "openpyxl")

In [6]:
import pandas

method  number  orbital_period   mass  distance  year
Unnamed: 0                                                                
0           Radial Velocity       1      269.300000   7.10     77.40  2006
1           Radial Velocity       1      874.774000   2.21     56.95  2008
2           Radial Velocity       1      763.000000   2.60     19.84  2011
3           Radial Velocity       1      326.030000  19.40    110.62  2007
4           Radial Velocity       1      516.220000  10.50    119.47  2009
...                     ...     ...             ...    ...       ...   ...
1030                Transit       1        3.941507    NaN    172.00  2006
1031                Transit       1        2.615864    NaN    148.00  2007
1032                Transit       1        3.191524    NaN    174.00  2007
1033                Transit       1        4.125083    NaN    293.00  2008
1034                Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [19]:
#titanic = sns.load_dataset('titanic')
#iris = sns.load_dataset('iris')

In [20]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [21]:
planets.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [200]:
planets.max()

method            Transit Timing Variations
number                                    7
orbital_period                       730000
mass                                     25
distance                               8500
year                                   2014
dtype: object

In [22]:
planets.method.count(), len(planets.method)

(1035, 1035)

In [23]:
planets.mass.max()

25.0

In [24]:
planets.method.value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

In [26]:
ls = planets.method.tolist()
ls

['Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Imaging',
 'Imaging',
 'Imaging',
 'Eclipse Timing Variations',
 'Imaging',
 'Imaging',
 'Imaging',
 'Imaging',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Radial Velocity',
 'Radial Velocity',
 'Imaging',
 'Radial Veloc

In [27]:
planets['number'].mean()

1.7855072463768116

In [29]:
a

array([4, 5, 7, 5, 6, 6, 9, 3])

In [28]:
np.any(a > 5)

True

In [30]:
np.sum(a > 5)

4

In [40]:
x1 = np.random.randint(10, size = (2,6)) #tableau 1D

In [41]:
np.sum(x1 == 3, axis = 1)

#nombre de valeurs = 3 dans chaque ligne

array([0, 0])

In [42]:
np.all(x1 < 8)

# toutes les valeurs sont-elles inférieures à 8?

False

<div class="alert alert-info">
<h3>opérateurs arithmétiques</h3></div>

<div class="alert alert-warning">
    <ul> <b>opérateurs arithmétiques - pandas</b></div>

In [184]:
df_qc['COUT/3'] = df_qc.COUT_TOTAL/3
#df_qc['COUT/3'].tail()
df_qc['COUT/3'].head(3)

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)    4.859767e+05
École Polytechnique de Montréal             9.084913e+05
Université de Sherbrooke                    1.981616e+06
Name: COUT/3, dtype: float64

In [183]:
type(df_qc['COUT/3'][0])

numpy.float64

In [182]:
# df_qc.columns

In [185]:
df_qc['soustraction'] = df_qc['COUT_TOTAL'].subtract(df_qc['MONTANT_TOTAL_QUEBEC'])

In [186]:
df_qc['soustraction'].head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     874758
École Polytechnique de Montréal             1657488
Université de Sherbrooke                    3566908
Université de Sherbrooke                    2603516
Université Laval                            3317547
Name: soustraction, dtype: int64

<div class="alert alert-danger">
<h3>Exercise</h3>
<li> Comment vérifier si le code de soustraction est correct ?
</div>

In [189]:
df_qc.COUT_TOTAL.head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)    1457930
École Polytechnique de Montréal             2725474
Université de Sherbrooke                    5944847
Université de Sherbrooke                    4248206
Université Laval                            5521200
Name: COUT_TOTAL, dtype: int64

In [190]:
df_qc.MONTANT_TOTAL_QUEBEC.head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     583172
École Polytechnique de Montréal             1067986
Université de Sherbrooke                    2377939
Université de Sherbrooke                    1644690
Université Laval                            2203653
Name: MONTANT_TOTAL_QUEBEC, dtype: int64

In [191]:
df_qc['soustraction'].head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     874758
École Polytechnique de Montréal             1657488
Université de Sherbrooke                    3566908
Université de Sherbrooke                    2603516
Université Laval                            3317547
Name: soustraction, dtype: int64

In [194]:
# vérification:
val1 = df_qc['COUT_TOTAL'][1]
val2 = df_qc['MONTANT_TOTAL_QUEBEC'][1]
finale = val1-val2

val3 = df_qc['soustraction'][1]
finale == val3

(df_qc.COUT_TOTAL[1])-(df_qc.MONTANT_TOTAL_QUEBEC[1]) == df_qc.soustraction[1]

True

In [192]:
df_test1 = df_qc.loc[df_qc.COUT_TOTAL > 20000000,
                     ['REGION_ADMINISTRATIVE', 'ANNEE_FINANCIERE']].head()
df_test1

REGION_ADMINISTRATIVE ANNEE_FINANCIERE
ETABLISSEMENT                                                
Université McGill                   Montréal        2009-2010
Université de Montréal              Montréal        2009-2010
Université McGill                   Montréal        2009-2010
Université Laval          Capitale-Nationale        2015-2016
Université McGill                   Montréal        2015-2016

In [193]:
df_test1.T

ETABLISSEMENT         Université McGill Université de Montréal  \
REGION_ADMINISTRATIVE          Montréal               Montréal   
ANNEE_FINANCIERE              2009-2010              2009-2010   

ETABLISSEMENT         Université McGill    Université Laval Université McGill  
REGION_ADMINISTRATIVE          Montréal  Capitale-Nationale          Montréal  
ANNEE_FINANCIERE              2009-2010           2015-2016         2015-2016

In [177]:
# df_qc[df_qc.COUT_TOTAL > 200000]

In [179]:
# df_qc.loc[df_qc.COUT_TOTAL>20000000, ['REGION_ADMINISTRATIVE', 'ANNEE_FINANCIERE']].head()

In [ ]:
df_qc[(df_qc.COUT_TOTAL>1400000) & (df_qc.COUT_TOTAL<5500000)]

<div class="alert alert-warning">
    <ul> <b>opérateurs arithmétiques - NumPy</b></div>

In [ ]:
np.add			+	Addition (3 + 6 = 9)
np.subtract		-	Subtraction (6 – 3 = 3)
np.negative		-	Negation ( -3)
np.multiply		*	Multiplication (3 * 3 = 9)
np.divide		/	Division (6/3 = 2; 3/2 = 1)
np.floor_divide	//	Floor division (6//3 = 2; 3//2 = 1)
np.power		**	Exponentiation (3**3 = 27; 2**3 = 8)
np.mod			%	Modulus/remainder(9%3=0; 9%4 = 1)

In [43]:
# opérations arithmétiques 

arr1 = np.random.randint(5, size=4)
arr2 = np.random.randint(5, size=4)
arr1, arr2

(array([0, 4, 2, 0]), array([3, 2, 4, 2]))

In [44]:
# Ajouter des tableaux ensemble
arr1 + arr2

array([3, 6, 6, 2])

In [115]:
# Multiplication matricielle
arr1 * arr2

array([0, 0, 0, 4])

In [45]:
-arr1

array([ 0, -4, -2,  0])

In [94]:
arr1**arr2

array([ 1, 27,  9,  4], dtype=int32)

In [95]:
np.add(arr1, 2)

array([2, 5, 5, 6])

In [96]:
np.negative(arr1)

array([ 0, -3, -3, -4])

In [97]:
np.multiply(arr1, 3)

array([ 0,  9,  9, 12])

In [98]:
abs(arr1)

# python command

array([0, 3, 3, 4])

In [99]:
np.absolute(arr1)

# np command

array([0, 3, 3, 4])

In [90]:
np.add.reduce(a)

# renvoie l'addition de tous les éléments

39

In [124]:
np.multiply.reduce(a) #produire de multiplier tous les éléments

24

In [125]:
np.add.accumulate(a)

#afficher toutes les valeurs intermédiaires

array([ 1,  3,  6, 10], dtype=int32)

In [126]:
np.multiply.outer(a,a)

#créer une table de multiplication

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

<div class="alert alert-info">
<h3>opérateurs trigonométrique; exponents, logarithms</h3></div>

In [46]:
exmpl = np.linspace(0, 4, 4)
exmpl

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [ ]:
sin, cos, tan, arcsin, arccos, arctan

np.sin(exmpl)
np.cos(exmpl)
np.tan(exmpl)

exp, exp2, power, log, log2, log10

np.exp(exmpl)
np.exp2(exmpl)
np.log(exmpl)
np.log2(exmpl)
np.power(exmpl, 2)

In [102]:
np.power(exmpl, 2)

array([ 0.        ,  1.77777778,  7.11111111, 16.        ])

In [101]:
np.sin(exmpl)

array([ 0.        ,  0.9719379 ,  0.45727263, -0.7568025 ])

<div class="alert alert-info">
<h3>opérateurs sur les valuers manquantes</h3></div>

<div class="alert alert-success">
<li>pandas marque les données manquantes avec NaN (pas un nombre) ou aucun (méthode du masque)
<li>NaN / None - ne sont pas disponibles pour tous les types de données
<li>-9999 (valeur sentinelle)
<li>la valeur sentinelle réduit la plage de valeurs valides pouvant être représentées et peut nécessiter une logique supplémentaire dans l'arithmétique CPU et GPU</div>

In [47]:
# quand quelque chose manque, pandas fusionne la cellule avec NaN:

A = {'a':1, 'b':2}
B = {'b':3, 'c':4}

df_na = pandas.DataFrame([A, B])

In [48]:
df_na

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [212]:
type(df_na['a'][0])

numpy.float64

<div class="alert alert-success">
<li>isnull()&nbsp;&nbsp;&nbsp;&nbsp; = générer un masque booléen indiquant les valeurs manquantes
<li>notnull()&nbsp; = opposé à isnull()
<li>dropna() = renvoie une version filtrée des données, les NaN sont supprimés
<li>fillna()&nbsp;&nbsp;&nbsp;&nbsp; = renvoie une copie des données avec les valeurs manquantes renseignées ou imputées</div>

In [49]:
# df_na.isnull()

df_na.isna()

a      b      c
0  False  False   True
1   True  False  False

In [50]:
df_na.notnull()
# df_na.notna()

a     b      c
0   True  True  False
1  False  True   True

In [51]:
df_na.dropna()

# supprime les colonnes où au moins un élément est manquant

Empty DataFrame
Columns: [a, b, c]
Index: []

In [52]:
df_na['a'].isnull().values.any()

# df_na.a.isnull().values.any()

True

In [246]:
#df_na['a']

In [53]:
df_na['a'].fillna(0)

0    1.0
1    0.0
Name: a, dtype: float64

In [54]:
df_na['a'].fillna(3)

0    1.0
1    3.0
Name: a, dtype: float64

In [250]:
#df_na.fillna(0)

In [55]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [ ]:
# plus d'informations ici:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

<div class="alert alert-danger">
<b>les commandes et codes à apprendre par cœur </b></div>